services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    env_file:
      - ".env"
    networks:
      - blogs

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app # mount local code
      - /app/node_modules # avoid overwriting node_modules
    command: npm run dev:watch
    ports:
      - 5001:5001
    networks:
      - blogs
    env_file:
      - ".env"
    depends_on:
      mongodb:
        condition: service_started

networks:
  blogs:
    driver: bridge

volumes:
  mongodata:
